name: main

on: [push, pull_request]

jobs:
  Build:
    name: Build
    runs-on:  ubuntu-latest
    container: barichello/godot-ci:mono-3.4.2
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          nuget restore
          mkdir -p .mono/assemblies/Debug
          cp /usr/local/bin/GodotSharp/Api/Release/* .mono/assemblies/Debug
      - name: Compile
        run: msbuild