name: main

on:
  push:
    branches:
      - master
jobs:
  Build:
    name: Build
    runs-on:  ubuntu-latest
    container: barichello/godot-ci:mono-3.4.2
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          nuget restore
          mkdir -p .mono/assemblies/Debug
          cp /usr/local/bin/GodotSharp/Api/Release/* .mono/assemblies/Debug

      - name: publish on version change
        id: publish_nuget
        uses: brandedoutcast/publish-nuget@v2.5.5
        with:
            # Filepath of the project to be packaged, relative to root of repository
            PROJECT_FILE_PATH: GodotTestDriver.csproj
            VERSION_REGEX: ^\s*<PackageVersion>(.*)<\/PackageVersion>\s*$
            NUGET_KEY: ${{ secrets.NUGET_KEY }}