name: '📦 Publish to Nuget'
# Whenever we push a v* tag we make a new release.
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*'

jobs:
  publish:
    name: '📦 Publish to Nuget'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: 🧾 Checkout

      - uses: actions/setup-dotnet@v3
        name: 💽 Setup .NET SDK
        with:
          # Use the .NET SDK from global.json in the root of the repository.
          global-json-file: global.json

      - name: get tag from version
        id: tag_version
        run: |
          echo ::set-output name=TAG_VERSION::${GITHUB_REF#refs/tags/v}

      - name: write version into file
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "0.0.0-devbuild"
          replace: ${{steps.tag_version.outputs.TAG_VERSION}}
          regex: false
          include: GodotTestDriver/GodotTestDriver.csproj

      - name: 📦 Publish
        id: publish_nuget
        uses: brandedoutcast/publish-nuget@v2
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: GodotTestDriver/GodotTestDriver.csproj

          # Regex pattern to extract version info in a capturing group
          VERSION_REGEX:  ^\s*<PackageVersion>(.*)<\/PackageVersion>\s*$

          # Flag to toggle git tagging, enabled by default
          TAG_COMMIT: false

          # API key to authenticate with NuGet server
          NUGET_KEY:  ${{ secrets.NUGET_KEY }}

          # Flag to toggle pushing symbols along with nuget package to the server, disabled by default
          INCLUDE_SYMBOLS: true
